services:
  - type: web
    name: voice-agent
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn --worker-class eventlet -w 1 client:app
    plan: free
    pythonVersion: 3.11.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    packages:
      - portaudio19-dev
      - python3-pyaudio
